FROM oven/bun:1

WORKDIR /user/src/app

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

RUN pnpm install --frozen-lockfile

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/http-backend ./apps/http-backend

RUN pnpm run db:generate

EXPOSE 8080

CMD [ "pnpm", "run", "start:http" ]