FROM node:20-alpine

WORKDIR /user/src/app

ARG DATABASE_URL

RUN npm install -g pnpm

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/http-backend ./apps/http-backend

RUN pnpm install
RUN DATABASE_URL=${DATABASE_URL} pnpm run db:generate

EXPOSE 8080

CMD [ "pnpm", "run", "start:http" ]