FROM oven/bun:1

WORKDIR /user/src/app

ARG DATABASE_URL

RUN npm install -g pnpm

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/drawr-fe ./apps/drawr-fe

RUN pnpm install
RUN pnpm run db:generate
RUN DATABASE_URL=${DATABASE_URL} pnpm run build


EXPOSE 3000

CMD [ "pnpm", "run", "start:fe" ]