FROM node:20-alpine

WORKDIR /user/src/app

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/http-backend ./apps/http-backend

RUN pnpm install
RUN pnpm run db:generate

EXPOSE 8080

CMD [ "pnpm", "run", "start:http" ]